---
# Docker Compose
# Author: Bryce Emery
# 2026March03
# Ref: https://www.docker.com/blog/how-to-dockerize-django-app/
# Ref: https://github.com/simon-tarr/geodjango-docker/tree/master

services:
  django-web:
    build: .
    container_name: django-docker
    restart: always
    ports:
      - "8000:8000"
    links:
      - postgis-db
    depends_on:
      - postgis-db
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env 
#    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000

  postgis-db:
    image: postgis/postgis:18-3.6
    restart: always
    container_name: hch_db
    expose:
      - 5432
    volumes:
      - postgis_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgis_data:
