# Generated by Django 6.0.2 on 2026-03-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_shelter_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_date', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(blank=True, max_length=50)),
                ('age', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
