# Generated by Django 6.0.2 on 2026-03-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0003_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='shelter_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='intake_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
