# Generated by Django 6.0.2 on 2026-03-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0004_animal_animal_id_animal_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
